### ISSUE TITLE
Hi I can not use the script in any way I can not install the modules help please tell me in detail how or do another lesson please

### ISSUE THREAD

**Issue by YouCorpse** [BlaCoiso/scw_parse#2]
Hi I can not use the script in any way I can not install the modules help please tell me in detail how or do another lesson please

**Comment by garlfin** [comment]
https://youtu.be/W_q7ByiKDsM Check this out

**Comment by garlfin** [comment]
Or just learn to code

**Comment by BlaCoiso** [comment]
Probably fixed in fcbcd64496359a41c41f859fc59c5c7047d93765
