### ISSUE TITLE
ay as it's a shame'

### ISSUE THREAD

**Issue by YouCorpse** [BlaCoiso/scw_parse#3]
8bit 
![image](https://user-images.githubusercontent.com/58003554/69453955-1baf5980-0d76-11ea-9173-b4eed4e0f0f3.png)

**Comment by YouCorpse** [comment]
and so with all

**Comment by BlaCoiso** [comment]
Try using blender to open it then export in another format, C4D doesn't seem to like .dae models
![image](https://user-images.githubusercontent.com/13855359/69482773-81075700-0e17-11ea-9cf4-a28b09e6f203.png)
