### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: Failed to find library character_materials.scw

### ISSUE THREAD

**Issue by fourk0** [BlaCoiso/scw_parse#8]
When using:
`node --trace-warnings convert --source ./in-scw/ --output ./out-dae/ --all`
While exporting `jessie_geo.scw`
This error gets retruned:
`UnhandledPromiseRejectionWarning: ReferenceError: Failed to find library character_materials.scw`

**Comment by garlfin** [comment]
It doesn't exist then

**Comment by developgiiker** [comment]
you should put the character_materials.scw into your in-scw folder, the will run success

**Comment by developgiiker** [comment]
@FourCinnamon0

**Comment by fourk0** [comment]
Thanks
